### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by csBlueChip** [rkrishnasanka/ArduinoNunchuk#1]
Images are missing in the README on the front page

**Comment by rkrishnasanka** [comment]
@csBlueChip, thanks for pointing out the issues. I managed to pull the data from the waybackmachine and threw them into the repo itself. Hopefully, you find the repo useful !

**Comment by csBlueChip** [comment]
Brilliant! Thanks so much for sharing your work. 
Also a couple of your reference links have gone 404 ...so here is a cut'n'paste of the biblio in my code
```c
// Biblio: [standing on the shoulders of giants]
//    https://bootlin.com/labs/doc/nunchuk.pdf
//    https://github.com/rkrishnasanka/ArduinoNunchuk
//    https://www.hackster.io/infusion/using-a-wii-nunchuk-with-arduino-597254#toc-i2c-protocol-9
//    https://web.archive.org/web/20220000000000*/https://www.hackster.io/infusion/using-a-wii-nunchuk-with-arduino-597254
//    https://github.com/madhephaestus/WiiChuck/blob/master/src/Accessory.cpp#L14
//    https://wiibrew.org/wiki/Wiimote/Extension_Controllers
//
// WiiMote Perhipheral:
//    Bus Address : 0x52
//    Register autoincrements after each (byte is) read
//       0x00..0x05 ( 6 bytes) ... [r] Controller Data
//       0x20..0x2F (16 bytes) ... [r] Calibration Data
//       0x30..0x3F (16 bytes) ... [r] (A copy of the) Calibration Data
//       0x40..0x4F (16 bytes) ... [w] Encryption key(s)
//       0xFA..0xFF ( 6 bytes) ... [r] Perhipheral ID
```

One trick I use if I find an especially good page is that I'll check to see if it is on archive.org. If not, I hit the "archive now" button ;)

**Comment by rkrishnasanka** [comment]
Feel free to PR, drop the additional documentation into the readme. Personally, I put nowadays put all the data sheets in a docs folder because the websites change, die, etc.

I'll try digging in and find any missing info later this weekend.
